import type { Presentation, Slide } from '@/types/presentation';

export interface PresentationVersion {
  id: string;
  timestamp: number;
  data: Presentation;
  metadata: {
    author: string;
    changeDescription: string;
    slideCount: number;
    autoGenerated: boolean;
  };
}

export interface VersionDiff {
  added: number[];
  removed: number[];
  modified: number[];
  unchanged: number[];
}

const VERSION_STORAGE_KEY = 'workai-versions';
const MAX_VERSIONS = 50;

function generateVersionId(): string {
  return `v-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

export function createVersion(
  presentation: Presentation,
  changeDescription: string,
  autoGenerated: boolean = false,
  author: string = '사용자'
): PresentationVersion {
  return {
    id: generateVersionId(),
    timestamp: Date.now(),
    data: JSON.parse(JSON.stringify(presentation)),
    metadata: {
      author,
      changeDescription,
      slideCount: presentation.slides?.length || 0,
      autoGenerated,
    },
  };
}

export function saveVersion(version: PresentationVersion): void {
  const versions = loadVersions();
  versions.unshift(version);
  
  if (versions.length > MAX_VERSIONS) {
    versions.pop();
  }
  
  try {
    localStorage.setItem(VERSION_STORAGE_KEY, JSON.stringify(versions));
  } catch (error) {
    console.error('Failed to save version:', error);
  }
}

export function loadVersions(): PresentationVersion[] {
  try {
    const stored = localStorage.getItem(VERSION_STORAGE_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch (error) {
    console.error('Failed to load versions:', error);
    return [];
  }
}

export function getVersion(versionId: string): PresentationVersion | null {
  const versions = loadVersions();
  return versions.find(v => v.id === versionId) || null;
}

export function deleteVersion(versionId: string): void {
  const versions = loadVersions().filter(v => v.id !== versionId);
  try {
    localStorage.setItem(VERSION_STORAGE_KEY, JSON.stringify(versions));
  } catch (error) {
    console.error('Failed to delete version:', error);
  }
}

export function compareVersions(
  oldVersion: Presentation,
  newVersion: Presentation
): VersionDiff {
  const oldSlides = new Map(
    (oldVersion.slides || []).map((s, i) => [s.id || `slide-${i}`, { slide: s, index: i }])
  );
  const newSlides = new Map(
    (newVersion.slides || []).map((s, i) => [s.id || `slide-${i}`, { slide: s, index: i }])
  );
  
  const added: number[] = [];
  const removed: number[] = [];
  const modified: number[] = [];
  const unchanged: number[] = [];
  
  newVersion.slides?.forEach((slide, index) => {
    const key = slide.id || `slide-${index}`;
    if (!oldSlides.has(key)) {
      added.push(index);
    }
  });
  
  oldVersion.slides?.forEach((slide, index) => {
    const key = slide.id || `slide-${index}`;
    if (!newSlides.has(key)) {
      removed.push(index);
    }
  });
  
  newVersion.slides?.forEach((slide, index) => {
    const key = slide.id || `slide-${index}`;
    if (oldSlides.has(key)) {
      const oldSlide = oldSlides.get(key)!.slide;
      if (JSON.stringify(oldSlide) !== JSON.stringify(slide)) {
        modified.push(index);
      } else {
        unchanged.push(index);
      }
    }
  });
  
  return { added, removed, modified, unchanged };
}

export function formatVersionTimestamp(timestamp: number): string {
  const date = new Date(timestamp);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMins / 60);
  const diffDays = Math.floor(diffHours / 24);
  
  if (diffMins < 1) return '방금 전';
  if (diffMins < 60) return `${diffMins}분 전`;
  if (diffHours < 24) return `${diffHours}시간 전`;
  if (diffDays < 7) return `${diffDays}일 전`;
  
  return date.toLocaleDateString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}
